# -*- coding: utf-8 -*-
"""ML2021Spring - HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ClP5itfGdd5Apc9cISTZlPbie42q3aFD

# **Homework 3 - Convolutional Neural Network**

This is the example code of homework 3 of the machine learning course by Prof. Hung-yi Lee.

In this homework, you are required to build a convolutional neural network for image classification, possibly with some advanced training tips.


There are three levels here:

**Easy**: Build a simple convolutional neural network as the baseline. (2 pts)

**Medium**: Design a better architecture or adopt different data augmentations to improve the performance. (2 pts)

**Hard**: Utilize provided unlabeled data to obtain better results. (2 pts)

## **About the Dataset**

The dataset used here is food-11, a collection of food images in 11 classes.

For the requirement in the homework, TAs slightly modified the data.
Please DO NOT access the original fully-labeled training data or testing labels.

Also, the modified dataset is for this course only, and any further distribution or commercial use is forbidden.
"""

# Download the dataset
# You may choose where to download the data.

# Google Drive
!gdown --id '1awF7pZ9Dz7X1jn1_QAiKN-_v56veCEKy' --output food-11.zip

# Dropbox
# !wget https://www.dropbox.com/s/m9q6273jl3djall/food-11.zip -O food-11.zip

# MEGA
# !sudo apt install megatools
# !megadl "https://mega.nz/#!zt1TTIhK!ZuMbg5ZjGWzWX1I6nEUbfjMZgCmAgeqJlwDkqdIryfg"

# Unzip the dataset.
# This may take some time.
!unzip -q food-11.zip

"""## **Import Packages**

First, we need to import packages that will be used later.

In this homework, we highly rely on **torchvision**, a library of PyTorch.
"""

# Import necessary packages.
import numpy as np
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision
from PIL import Image
# "ConcatDataset" and "Subset" are possibly useful when doing semi-supervised learning.
from torch.utils.data import ConcatDataset, DataLoader, Subset
from torchvision.datasets import DatasetFolder, ImageFolder
from collections import Counter
# This is for the progress bar.
from tqdm import tqdm
from transformers import get_linear_schedule_with_warmup #安排一個線性變化的learning rate
import sys #調整python內置的遞迴深度
sys.setrecursionlimit(1000000)
myseed = 123  # 用於初始化隨機數生成器，讓在不同的過程中都可以得到相同的隨機數序列
torch.backends.cudnn.deterministic = True #使用PyTorch CuDNN後端地確定性演算法，可以讓卷積的操作具有一致性，但速度有所損失
torch.backends.cudnn.benchmark = False #讓PyTorch在運行過程中不會自行尋找最優的卷積演算法進行加速，以確保穩定性
np.random.seed(myseed)
torch.manual_seed(myseed) #設置PyTorch的隨機數序列，確保都為一致
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(myseed)

"""## **Dataset, Data Loader, and Transforms**

Torchvision provides lots of useful utilities for image preprocessing, data wrapping as well as data augmentation.

Here, since our data are stored in folders by class labels, we can directly apply **torchvision.datasets.DatasetFolder** for wrapping data without much effort.

Please refer to [PyTorch official website](https://pytorch.org/vision/stable/transforms.html) for details about different transforms.
"""

# It is important to do data augmentation in training.
# However, not every augmentation is useful.
# Please think about what kind of augmentation is helpful for food recognition.
train_tfm = transforms.Compose([
    transforms.RandomResizedCrop((128, 128)),
    transforms.RandomChoice(
        [transforms.AutoAugment(),
        transforms.AutoAugment(transforms.AutoAugmentPolicy.CIFAR10),
        transforms.AutoAugment(transforms.AutoAugmentPolicy.IMAGENET),
        transforms.AutoAugment(transforms.AutoAugmentPolicy.SVHN)]
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.5),
    transforms.RandomAffine(degrees=20, translate=(0.2, 0.2), scale=(0.8, 1.2),shear=(-10,10,-10,10)),
    transforms.PILToTensor(),
])
train_tfm1 = transforms.Compose([
    # Resize the image into a fixed shape (height = width = 128)
    transforms.Resize((128, 128)),
    transforms.RandomChoice(
        [
            transforms.AutoAugment(),
            transforms.AutoAugment(transforms.AutoAugmentPolicy.CIFAR10),
            transforms.AutoAugment(transforms.AutoAugmentPolicy.IMAGENET),
            transforms.AutoAugment(transforms.AutoAugmentPolicy.SVHN),
        ]
    ),
    transforms.RandomHorizontalFlip(p = 0.7),
    transforms.RandomAffine(degrees=(-20,20),scale=(0.7,1.3),shear=(-10,10,-10,10)),
    transforms.ColorJitter(brightness=(0,5),contrast = (0,5),saturation = (0,5)),
    transforms.PILToTensor(),
])
# We don't need augmentations in testing and validation.
# All we need here is to resize the PIL image and transform it into Tensor.
test_tfm = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.PILToTensor(),
])

# Batch size for training, validation, and testing.
# A greater batch size usually gives a more stable gradient.
# But the GPU memory is limited, so please adjust it carefully.
batch_size = 32
test_batch_size = 1024

# Construct datasets.
# The argument "loader" tells how torchvision reads the data.
train_set1 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm)
train_set2 = DatasetFolder("food-11/training/labeled", loader=lambda x: Image.open(x), extensions="jpg", transform=train_tfm1)
train_set = ConcatDataset([train_set1,train_set2])
valid_set = DatasetFolder("food-11/validation", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)
unlabeled_test_set = ImageFolder("food-11/training/unlabeled", loader=lambda x: Image.open(x), transform=test_tfm)
unlabeled_train_set = ImageFolder("food-11/training/unlabeled", loader=lambda x: Image.open(x), transform=train_tfm)
test_set = DatasetFolder("food-11/testing", loader=lambda x: Image.open(x), extensions="jpg", transform=test_tfm)

# Construct data loaders.
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
valid_loader = DataLoader(valid_set, batch_size=test_batch_size, shuffle=True, pin_memory=True)
test_loader = DataLoader(test_set, batch_size=test_batch_size, shuffle=False)

"""## **Model**

The basic model here is simply a stack of convolutional layers followed by some fully-connected layers.

Since there are three channels for a color image (RGB), the input channels of the network must be three.
In each convolutional layer, typically the channels of inputs grow, while the height and width shrink (or remain unchanged, according to some hyperparameters like stride and padding).

Before fed into fully-connected layers, the feature map must be flattened into a single one-dimensional vector (for each image).
These features are then transformed by the fully-connected layers, and finally, we obtain the "logits" for each class.

### **WARNING -- You Must Know**
You are free to modify the model architecture here for further improvement.
However, if you want to use some well-known architectures such as ResNet50, please make sure **NOT** to load the pre-trained weights.
Using such pre-trained models is considered cheating and therefore you will be punished.
Similarly, it is your responsibility to make sure no pre-trained weights are used if you use **torch.hub** to load any modules.

For example, if you use ResNet-18 as your model:

model = torchvision.models.resnet18(pretrained=**False**) → This is fine.

model = torchvision.models.resnet18(pretrained=**True**)  → This is **NOT** allowed.
"""

class Classifier(nn.Module):
    def __init__(self):
        super(Classifier, self).__init__()
        # The arguments for commonly used modules:
        # torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
        # torch.nn.MaxPool2d(kernel_size, stride, padding)

        # input image size: [3, 128, 128]
        self.cnn_layers = nn.Sequential(
            nn.Conv2d(3, 64, 3, 1,1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),
            nn.Dropout(0.2),

            nn.Conv2d(64, 128, 3, 1, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),
            nn.Dropout(0.2),

            nn.Conv2d(128, 256, 3, 1, 1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),
            nn.Dropout(0.2),

            nn.Conv2d(256, 512, 3, 1, 1),
            nn.BatchNorm2d(512),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),
            nn.Dropout(0.2),

            nn.Conv2d(512, 1024, 3, 1, 1),
            nn.BatchNorm2d(1024),
            nn.ReLU(),
            nn.MaxPool2d(2, 2, 0),
            nn.Dropout(0.2)
        )
        self.fc_layers = nn.Sequential(
            nn.Linear(4096, 1024),
            nn.BatchNorm1d(1024),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(1024, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Linear(256, 11)
        )

    def forward(self, x):
        # input (x): [batch_size, 3, 128, 128]
        # output: [batch_size, 11]

        # Extract features by convolutional layers.
        x = self.cnn_layers(x)

        # The extracted feature map must be flatten before going to fully-connected layers.
        x = x.flatten(1)

        # The features are transformed by fully-connected layers to obtain the final logits.
        x = self.fc_layers(x)
        return x

"""## **Training**

You can finish supervised learning by simply running the provided code without any modification.

The function "get_pseudo_labels" is used for semi-supervised learning.
It is expected to get better performance if you use unlabeled data for semi-supervised learning.
However, you have to implement the function on your own and need to adjust several hyperparameters manually.

For more details about semi-supervised learning, please refer to [Prof. Lee's slides](https://speech.ee.ntu.edu.tw/~tlkagk/courses/ML_2016/Lecture/semi%20(v3).pdf).

Again, please notice that utilizing external data (or pre-trained model) for training is **prohibited**.
"""

def get_pseudo_labels(dataset, model, threshold=0.7):
    # This functions generates pseudo-labels of a dataset using given model.
    # It returns an instance of DatasetFolder containing images whose prediction confidences exceed a given threshold.
    # You are NOT allowed to use any models trained on external data for pseudo-labeling.
    #device = "cuda" if torch.cuda.is_available() else "cpu"
    global models, unlabeled_train_set, unlabeled_test_set, train_set

    remove_index, index = [],0
    pre = []

    for imgs, labels in tqdm(unlabeled_test_set):
      imgs = imgs.float().cuda() #圖片轉換成浮點數
      for i,model in enumerate(models):
        model.eval()
        with torch.no_grad():
          logits = model(torch.unsqueeze(imgs,0)) #
        prediction = torch.argmax(logits,1) #得到預測類別
        pre_num = prediction.cpu().numpy() #將一個tensor object轉換成 numpy array
        pre.append(pre_num) #將預測結果加入pre中
      arr = np.array(pre)
      pre.clear()
      result = [Counter(arr[:,i].most_common(1)[0] for i in range(arr.shape[1]))]

      if result [0][1] == model_number:
        temp = list(unlabeled_train_set[index])
        temp[1] = result[0][1]
        train_set = ConcatDataset([train_set, ([tuple(temp)])])
        remove_index.append(index)
      index += 1

    remove_index.reverse()
    for i in remove_index:
        unlabeled_train_set.imgs.remove((unlabeled_train_set.imgs[i]))
        unlabeled_test_set.imgs.remove((unlabeled_test_set.imgs[i]))
    print(f"[{len(train_set)-3080*2}/6786] images have been labeled.")
    # Construct a data loader.
    #data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    # Make sure the model is in eval mode.
    #model.eval()
    # Define softmax function.
    #softmax = nn.Softmax(dim=-1)


    #filter_index = []
    #filter_labels = []
    #cnt = 0

    # Iterate over the dataset by batches.
    #for img in tqdm(unlabeled_set_list):
        #img, _ = batch

        # Forward the data
        # Using torch.no_grad() accelerates the forward process.
    #    with torch.no_grad():
    #        logits = model(img.to(device))

        # Obtain the probability distributions by applying softmax on logits.
    #    probs = softmax(logits)

        # ---------- TODO ----------
        # Filter the data and construct a new dataset.
    #    if torch.max(probs).item() > threshold:
    #      train_set = ConcatDataset([train_set,([(img,torch.argmax(probs).item())])])
    #      remove_index.append(index)
    #    index += 1

    #remove_index.reverse()
    #for i in remove_index:
    #  del unlabeled_set_list[i]
    ## # Turn off the eval mode.
    #model.train()

# "cuda" only when GPUs are available.
device = "cuda" if torch.cuda.is_available() else "cpu"
model_number = 5
models = []

# Initialize a model, and put it on the device specified.
#model = Classifier().to(device)
#model.device = device
#
# For the classification task, we use cross-entropy as the measurement of performance.
criterion = nn.CrossEntropyLoss()
#
## Initialize optimizer, you may fine-tune some hyperparameters such as learning rate on your own.
#optimizer = torch.optim.Adam(model.parameters(), lr=0.00005, weight_decay=1e-5)


for i in range(model_number):
    model = torchvision.models.resnet34(pretrained = False)
    model.fc = nn.Linear(512, 11)
    models.append(model.cuda())
# The number of training epochs.
n_epochs = 300
warm_up_ratio = 0.15
step = len(train_loader) / (6786*0.1//batch_size)
total_step = n_epochs * step

optimizer = torch.optim.RAdam([{"params":model.parameters()} for model in models], lr=1e-3, weight_decay=1e-4)
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps = warm_up_ratio * total_step, num_training_steps = total_step)


best_acc = 0
valid_acc_last = 0
valid_acc_threshold = 0.8

# Whether to do semi-supervised learning.
#do_semi = True

for epoch in range(n_epochs):
    # ---------- TODO ----------
    # In each epoch, relabel the unlabeled dataset for semi-supervised learning.
    # Then you can combine the labeled dataset and pseudo-labeled dataset for the training.
    #if do_semi and best_acc > 0.7 and epoch %5 == 0:
    #    # Obtain pseudo-labels for unlabeled data using trained model.
    #    pseudo_set = get_pseudo_labels(unlabeled_set, model)
    #    # Construct a new dataset and a data loader for training.
    #    # This is used in semi-supervised learning only.
    #    concat_dataset = ConcatDataset([train_set, pseudo_set])
    #    train_loader = DataLoader(concat_dataset, batch_size=batch_size, shuffle=True, num_workers=8, pin_memory=True)

    if valid_acc_last > valid_acc_threshold:
      valid_acc_threshold = valid_acc_last
      if len(train_set) != 3080*2 + 6876:
        get_pseudo_labels()
      train_loader = DataLoader(train_set,batch_size = batch_size,shuffle = True, pin_memory = True, num_workers= 2)
    # ---------- Training ----------
    # Make sure the model is in train mode before training.
   # model.train()

   ## These are used to record information in training.
   #train_loss = []
   #train_accs = []

   ## Iterate the training set by batches.
   #for batch in tqdm(train_loader):

   #    # A batch consists of image data and corresponding labels.
   #    imgs, labels = batch

   #    # Forward the data. (Make sure data and model are on the same device.)
   #    logits = model(imgs.to(device))

   #    # Calculate the cross-entropy loss.
   #    # We don't need to apply softmax before computing cross-entropy as it is done automatically.
   #    loss = criterion(logits, labels.to(device))

   #    # Gradients stored in the parameters in the previous step should be cleared out first.
   #    optimizer.zero_grad()

   #    # Compute the gradients for parameters.
   #    loss.backward()

   #    # Clip the gradient norms for stable training.
   #    grad_norm = nn.utils.clip_grad_norm_(model.parameters(), max_norm=10)

   #    # Update the parameters with computed gradients.
   #    optimizer.step()

   #    # Compute the accuracy for current batch.
   #    acc = (logits.argmax(dim=-1) == labels.to(device)).float().mean()

   #    # Record the loss and accuracy.
   #    train_loss.append(loss.item())
   #    train_accs.append(acc)
    for imgs, labels in tqdm(train_loader):
      imgs,labels = imgs.float().cuda(), labels.cuda()
      optimizer.zero_grad()
      for model in models:
        model.train()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
      optimizer.step()
      scheduler.step()

    # The average loss and accuracy of the training set is the average of the recorded values.
    #train_loss = sum(train_loss) / len(train_loss)
    #train_acc = sum(train_accs) / len(train_accs)

    ## Print the information.
    #print(f"[ Train | {epoch + 1:03d}/{n_epochs:03d} ] loss = {train_loss:.5f}, acc = {train_acc:.5f}")

    # ---------- Validation ----------
    # Make sure the model is in eval mode so that some modules like dropout are disabled and work normally.
    #model.eval()

    ## These are used to record information in validation.
    #valid_loss = []
    #valid_accs = []

    ## Iterate the validation set by batches.
    #for batch in valid_loader:

    #    # A batch consists of image data and corresponding labels.
    #    imgs, labels = batch

    #    # We don't need gradient in validation.
    #    # Using torch.no_grad() accelerates the forward process.
    #    with torch.no_grad():
    #      logits = model(imgs.to(device))

    #    # We can still compute the loss (but not the gradient).
    #    loss = criterion(logits, labels.to(device))

    #    # Compute the accuracy for current batch.
    #    acc = (logits.argmax(dim=-1) == labels.to(device)).float().mean()

    #    # Record the loss and accuracy.
    #    valid_loss.append(loss.item())
    #    valid_accs.append(acc)
    pre = []
    vote_correct = 0
    models_correct = [0 for i in range(len(models))]

    # Iterate the validation set by batches.
    for imgs, labels in tqdm(valid_loader):
        imgs, labels = imgs.float().cuda(), labels.cuda()
        for i, model in enumerate(models):
            model.eval()
            with torch.no_grad():
                logits = model(imgs)
            prediction = torch.argmax(logits, 1)
            pre_num = prediction.cpu().numpy()
            models_correct[i] += (pre_num == labels.cpu().numpy()).sum()
            pre.append(pre_num)
        arr = np.array(pre)
        pre.clear()
        result = [Counter(arr[:,i]).most_common(1)[0][0] for i in range(arr.shape[1])]
        vote_correct += (result == labels.cpu().numpy()).sum()


    valid_acc = vote_correct/len(valid_set)
    valid_acc_last = valid_acc

    # Print the information.
    print(f"[ Valid | {epoch + 1:03d}/{n_epochs:03d} ] acc = {valid_acc:.5f}")

    if valid_acc > best_acc:
        best_acc = valid_acc
        for i, model in enumerate(models):
            torch.save(model.state_dict(), './model' + str(i) + '.ckpt')
        print('[{:03d}/{:03d}] saving model with acc {:.3f}'.format(epoch + 1, n_epochs, best_acc))
    # The average loss and accuracy for entire validation set is the average of the recorded values.
    #valid_loss = sum(valid_loss) / len(valid_loss)
    #valid_acc = sum(valid_accs) / len(valid_accs)
    #if valid_acc > best_acc:
    #  best_acc = valid_acc

    # Print the information.
    #print(f"[ Valid | {epoch + 1:03d}/{n_epochs:03d} ] loss = {valid_loss:.5f}, acc = {valid_acc:.5f}")

"""## **Testing**

For inference, we need to make sure the model is in eval mode, and the order of the dataset should not be shuffled ("shuffle=False" in test_loader).

Last but not least, don't forget to save the predictions into a single CSV file.
The format of CSV file should follow the rules mentioned in the slides.

### **WARNING -- Keep in Mind**

Cheating includes but not limited to:
1.   using testing labels,
2.   submitting results to previous Kaggle competitions,
3.   sharing predictions with others,
4.   copying codes from any creatures on Earth,
5.   asking other people to do it for you.

Any violations bring you punishments from getting a discount on the final grade to failing the course.

It is your responsibility to check whether your code violates the rules.
When citing codes from the Internet, you should know what these codes exactly do.
You will **NOT** be tolerated if you break the rule and claim you don't know what these codes do.

"""

# Make sure the model is in eval mode.
# Some modules like Dropout or BatchNorm affect if the model is in training mode.
model.eval()

# Initialize a list to store the predictions.
predictions = []

# Iterate the testing set by batches.
for batch in tqdm(test_loader):
    # A batch consists of image data and corresponding labels.
    # But here the variable "labels" is useless since we do not have the ground-truth.
    # If printing out the labels, you will find that it is always 0.
    # This is because the wrapper (DatasetFolder) returns images and labels for each batch,
    # so we have to create fake labels to make it work normally.
    imgs, labels = batch

    # We don't need gradient in testing, and we don't even have labels to compute loss.
    # Using torch.no_grad() accelerates the forward process.
    with torch.no_grad():
        logits = model(imgs.to(device))

    # Take the class with greatest logit as prediction and record it.
    predictions.extend(logits.argmax(dim=-1).cpu().numpy().tolist())

# Save predictions into the file.
with open("predict.csv", "w") as f:

    # The first row must be "Id, Category"
    f.write("Id,Category\n")

    # For the rest of the rows, each image id corresponds to a predicted class.
    for i, pred in  enumerate(predictions):
         f.write(f"{i},{pred}\n")